# Generated by Django 4.2.3 on 2023-10-10 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="users_avatar", verbose_name="User Avatar"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name="User Date of Birth"),
        ),
    ]
