# Generated by Django 4.2.3 on 2023-10-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="users_avatar", verbose_name="User Avatar"),
        ),
    ]
