# Generated by Django 4.2.3 on 2023-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(related_name="posts", to="blog.tag"),
        ),
    ]
