# Generated by Django 4.2.14 on 2024-07-19 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='users_avatar', verbose_name='User Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='User Date of Birth'),
        ),
    ]
