# Generated by Django 5.0.10 on 2025-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_date_of_birth_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='images/', verbose_name='User Avatar'),
        ),
    ]
