# Generated by Django 4.2.3 on 2023-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_tag"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["-published_at"], name="blog_commen_publish_d8cfea_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-updated_at"], name="blog_post_updated_261a59_idx"),
        ),
    ]
