# Generated by Django 4.2.3 on 2023-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment_blog_commen_publish_d8cfea_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_updated_261a59_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-published_at"], name="blog_post_publish_2c9212_idx"),
        ),
    ]
