# Generated by Django 4.2.3 on 2024-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
